version: "2"
services:
    db:
        image: mysql:5.7
        ports: 
            - "9921:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
